name: PorchPong
options:
  deploymentTarget:
    iOS: '18.0'
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: '6.0'
    DEVELOPMENT_TEAM: V6JPQCD336
    MARKETING_VERSION: '1.0'
    CURRENT_PROJECT_VERSION: '1'
    TARGETED_DEVICE_FAMILY: '1'
    SUPPORTS_MACCATALYST: NO
    CODE_SIGN_STYLE: Automatic
    ENABLE_USER_SCRIPT_SANDBOXING: YES
targets:
  PorchPong:
    type: application
    platform: iOS
    sources:
      - path: PorchPong
        excludes: ["Info*.plist"]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jimgreco.doorstep
        CODE_SIGN_ENTITLEMENTS: PorchPong/PorchPong.entitlements
        TARGETED_DEVICE_FAMILY: '1'
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: PorchPong/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DOORSTEP_API_ORIGIN: https://packages.jim-greco.com
      configs:
        Debug:
          APNS_ENVIRONMENT: development
          INFOPLIST_FILE: PorchPong/Info-Debug.plist
        Release:
          APNS_ENVIRONMENT: production
          INFOPLIST_FILE: PorchPong/Info.plist
    scheme:
      testTargets: [PorchPongTests, PorchPongUITests]
  PorchPongTests:
    type: bundle.unit-test
    platform: iOS
    sources: [PorchPongTests]
    dependencies:
      - target: PorchPong
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jimgreco.doorstep.tests
        GENERATE_INFOPLIST_FILE: YES
  PorchPongUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: [PorchPongUITests]
    dependencies:
      - target: PorchPong
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jimgreco.doorstep.uitests
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: PorchPong
